# Generated by Django 6.0.2 on 2026-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_img_url_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='reply_to_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
